apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster                   
metadata:
  name: tkgs-ubucluster-01                       
  namespace: zyajing                   
spec:
  distribution:
    fullVersion: v1.20.8---vmware.1-tkg.2
  topology:
    controlPlane:
      replicas: 1                                 
      vmClass: guaranteed-xlarge                 
      storageClass: pacific-storage-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 20Gi
    nodePools:
    - name: workers
      replicas: 3
      vmClass: guaranteed-xlarge
      storageClass: pacific-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 100Gi
  settings:
    storage:
      defaultClass: pacific-storage-policy
    network:
      proxy:
        httpProxy: http://proxy.liuqi.io:3128  #Proxy URL for HTTP connections
        httpsProxy: http://proxy.liuqi.io:3128 #Proxy URL for HTTPS connections
        noProxy: [10.244.0.0/20,10.117.233.0/26,10.117.233.64/26,192.168.0.0/16,10.0.0.0/8,127.0.0.1,localhost,.svc,.svc.cluster.local] #SVC Pod, Egress, Ingress CIDRs      
